filename = '/OUTPUTS/DATA/NM.nii'

flags = struct( ...
	'quality', 0.9, ...
	'sep', 4, ...
	'fwhm', 5, ...
	'rtm', 1, ...
	'interp', 2, ...
	'wrap', [0 0 0] ...
	);

spm_realign(filename, flags);

flags = struct( ...
	'mask', true, ...
	'mean', true, ...
	'interp', 4, ...
	'which', 0, ...
	'wrap', [0 0 0], ...
	'prefix', 'r' ...
	);

spm_reslice(filename, flags);

exit;
